// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('First test Karis', function() {
  jest.setTimeout(5000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('First test Karis', async function() {
    // Test name: First test Karis
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1936x1056 | 
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    // 3 | click | css=.form-control | 
    await driver.findElement(By.css(".form-control")).click()
    // 4 | click | css=.list-group-item | 
    await driver.findElement(By.css(".list-group-item")).click()
    // 5 | click | css=.list-group-item | 
    await driver.findElement(By.css(".list-group-item")).click()
    // 6 | click | linkText=Add | 
    await driver.findElement(By.linkText("Add")).click()
    // 7 | click | id=title | 
    await driver.findElement(By.id("title")).click()
    // 8 | click | id=title | 
    await driver.findElement(By.id("title")).click()
    // 9 | type | id=title | Test 2
    await driver.findElement(By.id("title")).sendKeys("Test 2")
    // 10 | type | id=description | Karis Test 3
    await driver.findElement(By.id("description")).sendKeys("Karis Test 3")
    // 11 | click | id=title | 
    await driver.findElement(By.id("title")).click()
    // 12 | type | id=title | Test 3
    await driver.findElement(By.id("title")).sendKeys("Test 3")
    // 13 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
  })
})
